### ISSUE TITLE
Foundry v12 

### ISSUE THREAD

**Issue by neovatar** [Anderware/FUx-Dice-Roller#1]
For proper installation in Foundry v12 probably only an update of module.json is needed. At the moment Foundy v12 will install this module in version 0.4.0 because this is the last version that does not specify "compatibility.maxium". Version 0.4.2 of this module has set a "comppatibility.maximum" of 11 - so it will not install.

**Comment by neovatar** [comment]
Since this module seems abandoned, I forked it and fixed the v12 deprecation issues: https://github.com/neovatar/FUx-Dice-Roller

**Comment by squidgy617** [comment]
@neovatar Hello, I am trying to use your fork and it looks like I'm unable to report an issue on your repo. If that is intentional, feel free to disregard, but I found an issue. Whenever I attempt to make a dice roll, I get the following error in the log:

```
foundry.mjs:26743 DataModelValidationError: [ChatMessage] validation errors: SchemaField#_validateRecursive
  type: "2" is not a valid type for the ChatMessage Document class
    at DataModelValidationFailure.asError (foundry.mjs:8365:12)
    at ChatMessage.validate (foundry.mjs:14033:59)
    at new DataModel (foundry.mjs:13515:10)
    at new Document (foundry.mjs:14422:1)
    at new ClientDocumentMixin (foundry.mjs:36076:7)
    at new ChatMessage (foundry.mjs:48573:21)
    at #preCreateDocumentArray (foundry.mjs:80795:15)
    at ClientDatabaseBackend._createDocuments (foundry.mjs:80758:56)
    at ClientDatabaseBackend.create (foundry.mjs:80379:17)
    at async ChatMessage.create (foundry.mjs:15111:21)
foundry.mjs:145067 [ChatMessage] validation errors: SchemaField#_validateRecursive
  type: "2" is not a valid type for the ChatMessage Document class
```

It looks like it is failing to generate chat message with the roll result, for whatever reason.

**Comment by neovatar** [comment]
@squidgy617 you can open issues now at https://github.com/neovatar/FUx-Dice-Roller

what version of Foundry are you using?

**Comment by squidgy617** [comment]
@neovatar Just realized I am on the latest version, which I'm guessing is too new. I'm on version 14. My bad!

Thanks for opening up issues though!

**Comment by neovatar** [comment]
@squidgy617 Yes, unfortunately I did not update it for v14 yet.
